site_name: Navigator
site_url: https://rubys.github.io/navigator/
site_description: A Go-based web server for multi-tenant Rails applications
repo_url: https://github.com/rubys/navigator
repo_name: rubys/navigator
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github

plugins:
  - search:
      separator: '[\s\-\.]+'

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - Home: index.md
  - Getting Started:
    - getting-started/index.md
    - Installation: getting-started/installation.md
    - First Application: getting-started/first-app.md
    - Basic Configuration: getting-started/basic-config.md
  - Examples:
    - examples/index.md
    - Single Rails App: examples/single-tenant.md
    - Multi-Tenant Setup: examples/multi-tenant.md
    - With Redis: examples/with-redis.md
    - With Sidekiq: examples/with-sidekiq.md
    - Action Cable: examples/action-cable.md
    - systemd Service: examples/systemd.md
  - Configuration:
    - configuration/index.md
    - YAML Reference: configuration/yaml-reference.md
    - Server: configuration/server.md
    - Applications: configuration/applications.md
    - Templates: configuration/templates.md
    - Authentication: configuration/authentication.md
    - Static Files: configuration/static-files.md
    - Routing: configuration/routing.md
    - Processes: configuration/processes.md
  - Features:
    - features/index.md
    - Process Management: features/process-management.md
    - Try Files: features/try-files.md
    - Fly-Replay: features/fly-replay.md
    - Hot Reload: features/hot-reload.md
    - Machine Suspend: features/machine-suspend.md
  - Reference:
    - reference/index.md
    - CLI Options: reference/cli.md
    - Environment Variables: reference/environment.md
    - Signals: reference/signals.md
  - Deployment:
    - Production: deployment/production.md
    - Monitoring: deployment/monitoring.md
  - Documentation Overview: DOCUMENTATION_OVERVIEW.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/rubys/navigator

copyright: Copyright &copy; 2024-2025 Sam Ruby