[project]
name = "navigator-docs"
version = "0.7.1"
description = "Documentation for Navigator - Go Web Server for Rails"
dependencies = [
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.6.14",
    "pygments>=2.19.1",
    "pymdown-extensions>=10.15",
]