# Navigator Configuration Example
# Copy this file to navigator.yaml and adjust the settings for your environment

server:
  # Address to listen on (default: ":3000")
  listen: ":3000"
  
  # URL prefix to strip from requests (default: "/showcase")
  url_prefix: "/showcase"

rails:
  # Rails application root directory (required)
  root: "/path/to/rails/app"
  
  # Path to showcases.yml file relative to rails root (default: "config/tenant/showcases.yml")
  showcases: "config/tenant/showcases.yml"
  
  # Database directory path relative to rails root (default: "db")
  db_path: "db"
  
  # Storage directory path relative to rails root (default: "storage")
  storage: "storage"

manager:
  # Maximum number of concurrent Puma processes (default: 10)
  max_puma: 10
  
  # Idle timeout before stopping Puma process (default: "5m")
  idle_timeout: "5m"

auth:
  # Path to htpasswd file for authentication (optional)
  htpasswd_file: ""

logging:
  # Log level: debug, info, warn, error (default: "info")
  level: "info"

# Environment Variables
# You can also configure Navigator using environment variables with the NAVIGATOR_ prefix:
#
# Server:
#   NAVIGATOR_SERVER_LISTEN=":3000"
#   NAVIGATOR_SERVER_URL_PREFIX="/showcase"
#
# Rails:
#   NAVIGATOR_RAILS_ROOT="/path/to/rails/app"
#   NAVIGATOR_RAILS_SHOWCASES="config/tenant/showcases.yml"
#   NAVIGATOR_RAILS_DB_PATH="db"
#   NAVIGATOR_RAILS_STORAGE="storage"
#
# Manager:
#   NAVIGATOR_MANAGER_MAX_PUMA=10
#   NAVIGATOR_MANAGER_IDLE_TIMEOUT="5m"
#
# Auth:
#   NAVIGATOR_AUTH_HTPASSWD_FILE="/path/to/htpasswd"
#
# Logging:
#   NAVIGATOR_LOGGING_LEVEL="info"